#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@smartvpn[-1]
	add ucitrack smartvpn
	set ucitrack.@smartvpn[-1].init=smartvpn
	commit ucitrack
EOF

# remove LuCI cache
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
