#!/bin/sh /etc/rc.common

START=96
STOP=96

PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

config_load smartvpn
config_get VPN_ENABLE global vpn_enable 0
config_get VPN_CONFIG_PARM global config_parm ""

ipset_create(){
    local _ipset=$1
    local _type=${2:-ip}

    ipset list | grep $_ipset > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        ipset create $_ipset hash:$_type > /dev/null 2>&1
    else
        [[ "$2" != "soft" ]] && ipset flush $_ipset
    fi    
}

start() {
	# check if first time installation
	if [[ ! -d /etc/smartvpn/backup ]]; then
		VPN_CONFIG_PARM="--localip all"
	fi
	if [[ -n "$VPN_CONFIG_PARM" ]]; then
		logger -s -t softether "Config SmartVPN with parm: $VPN_CONFIG_PARM"
		/usr/share/smartvpn/smartvpnconfig.sh --norestart $VPN_CONFIG_PARM
		if [ $? -eq 0 ]; then
			uci delete smartvpn.global.config_parm
			uci commit smartvpn
		fi
	fi

	# create ipsest anyway
	ipset_create ip_oversea
    ipset_create ip_hongkong
    ipset_create ip_mainland
	ipset_create net_oversea net
    ipset_create net_hongkong net
    ipset_create net_mainland net

	if [ $VPN_ENABLE == 1 ]; then
		logger -s -t softether "Stoping SmartVPN..."
		smartvpn.sh on hard
	else
		logger -s -t softether "SmartVPN is disabled"
	fi
}

stop() {
	logger -s -t softether "Stoping SmartVPN..."
	smartvpn.sh off
}

restart() {
	start
}

reload() {
	if [ $VPN_ENABLE == 1 ]; then
		logger -s -t softether "Reloading SmartVPN...（soft）"
		smartvpn.sh on
	else
		logger -s -t softether "Stoping SmartVPN..."
		smartvpn.sh off
	fi
}
